version: 2
updates:
  # Enable version updates for npm (compatible with Bun)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "@testing-library/*"
          - "vitest*"
          - "@vitest/*"
        update-types:
          - "minor"
          - "patch"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
