import { GithubTeam, GithubMember, GithubTree } from "./types";

export const mockGithubTeams: GithubTeam[] = [
  {
    name: "leetcode01",
    id: 1,
    node_id: "T",
    slug: "leetcode01",
    description: "리트코드 스터디",
    privacy: "closed",
    notification_setting: "notifications_enabled",
    url: "some-url",
    html_url: "some-url",
    members_url: "members-url",
    repositories_url: "repositories-url",
    permission: "pull",
    parent: null,
  },
  {
    name: "leetcode",
    id: 2,
    node_id: "D",
    slug: "leetcode",
    description: "리트코드 스터디",
    privacy: "closed",
    notification_setting: "notifications_enabled",
    url: "some-url",
    html_url: "some-url",
    members_url: "members-url",
    repositories_url: "repositories-url",
    permission: "pull",
    parent: null,
  },
];

export const mockGithubMembers: GithubMember[] = [
  {
    login: "D",
    id: 1,
    node_id: "M",
    avatar_url: "avatar-url",
    gravatar_id: "",
    url: "some-url",
    html_url: "some-url",
    followers_url: "some-url",
    following_url: "some-url",
    gists_url: "some-url",
    starred_url: "some-url",
    subscriptions_url: "some-url",
    organizations_url: "some-url",
    repos_url: "some-url",
    events_url: "some-url",
    received_events_url: "some-url",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
  {
    login: "S",
    id: 2,
    node_id: "E",
    avatar_url: "avatar-url",
    gravatar_id: "",
    url: "some-url",
    html_url: "some-url",
    followers_url: "some-url",
    following_url: "some-url",
    gists_url: "some-url",
    starred_url: "some-url",
    subscriptions_url: "some-url",
    organizations_url: "some-url",
    repos_url: "some-url",
    events_url: "some-url",
    received_events_url: "some-url",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
];

export const mockGithubTree: GithubTree[] = [
  {
    path: "best-time-to-buy-and-sell-stock/test.java",
    type: "blob",
    mode: "100644",
    sha: "1",
    size: 0,
    url: "some-url",
  },
  {
    path: "best-time-to-buy-and-sell-stock/test2.java",
    type: "blob",
    mode: "100644",
    sha: "2",
    size: 0,
    url: "some-url",
  },
];
