import type { Problem } from "../api/services/types";

export const problems: Problem[] = [
  { id: "128", title: "longest-consecutive-sequence", difficulty: "medium" },
  { id: "1", title: "two-sum", difficulty: "easy" },
  { id: "3", title: "longest-substring-without-repeating-characters", difficulty: "medium" },
  { id: "5", title: "longest-palindromic-substring", difficulty: "medium" },
  { id: "133", title: "clone-graph", difficulty: "medium" },
  { id: "261", title: "graph-valid-tree", difficulty: "medium" },
  { id: "647", title: "palindromic-substrings", difficulty: "medium" },
  { id: "11", title: "container-with-most-water", difficulty: "medium" },
  { id: "139", title: "word-break", difficulty: "medium" },
  { id: "141", title: "linked-list-cycle", difficulty: "easy" },
  { id: "268", title: "missing-number", difficulty: "easy" },
  { id: "15", title: "3sum", difficulty: "medium" },
  { id: "143", title: "reorder-list", difficulty: "medium" },
  { id: "269", title: "alien-dictionary", difficulty: "hard" },
  { id: "271", title: "encode-and-decode-strings", difficulty: "medium" },
  { id: "19", title: "remove-nth-node-from-end-of-list", difficulty: "medium" },
  { id: "20", title: "valid-parentheses", difficulty: "easy" },
  { id: "21", title: "merge-two-sorted-lists", difficulty: "easy" },
  { id: "23", title: "merge-k-sorted-lists", difficulty: "hard" },
  { id: "152", title: "maximum-product-subarray", difficulty: "medium" },
  { id: "153", title: "find-minimum-in-rotated-sorted-array", difficulty: "medium" },
  { id: "33", title: "search-in-rotated-sorted-array", difficulty: "medium" },
  { id: "417", title: "pacific-atlantic-water-flow", difficulty: "medium" },
  { id: "39", title: "combination-sum", difficulty: "medium" },
  { id: "295", title: "find-median-from-data-stream", difficulty: "hard" },
  { id: "297", title: "serialize-and-deserialize-binary-tree", difficulty: "hard" },
  { id: "424", title: "longest-repeating-character-replacement", difficulty: "medium" },
  { id: "300", title: "longest-increasing-subsequence", difficulty: "medium" },
  { id: "48", title: "rotate-image", difficulty: "medium" },
  { id: "49", title: "group-anagrams", difficulty: "medium" },
  { id: "435", title: "non-overlapping-intervals", difficulty: "medium" },
  { id: "53", title: "maximum-subarray", difficulty: "easy" },
  { id: "54", title: "spiral-matrix", difficulty: "medium" },
  { id: "55", title: "jump-game", difficulty: "medium" },
  { id: "56", title: "merge-intervals", difficulty: "medium" },
  { id: "57", title: "insert-interval", difficulty: "hard" },
  { id: "572", title: "subtree-of-another-tree", difficulty: "easy" },
  { id: "62", title: "unique-paths", difficulty: "medium" },
  { id: "190", title: "reverse-bits", difficulty: "easy" },
  { id: "191", title: "number-of-1-bits", difficulty: "easy" },
  { id: "322", title: "coin-change", difficulty: "medium" },
  { id: "323", title: "number-of-connected-components-in-an-undirected-graph", difficulty: "medium" },
  { id: "70", title: "climbing-stairs", difficulty: "easy" },
  { id: "198", title: "house-robber", difficulty: "medium" },
  { id: "200", title: "number-of-islands", difficulty: "medium" },
  { id: "73", title: "set-matrix-zeroes", difficulty: "medium" },
  { id: "76", title: "minimum-window-substring", difficulty: "hard" },
  { id: "206", title: "reverse-linked-list", difficulty: "easy" },
  { id: "79", title: "word-search", difficulty: "medium" },
  { id: "207", title: "course-schedule", difficulty: "medium" },
  { id: "208", title: "implement-trie-prefix-tree", difficulty: "medium" },
  { id: "338", title: "counting-bits", difficulty: "easy" },
  { id: "211", title: "design-add-and-search-words-data-structure", difficulty: "medium" },
  { id: "212", title: "word-search-ii", difficulty: "hard" },
  { id: "213", title: "house-robber-ii", difficulty: "medium" },
  { id: "217", title: "contains-duplicate", difficulty: "easy" },
  { id: "91", title: "decode-ways", difficulty: "medium" },
  { id: "347", title: "top-k-frequent-elements", difficulty: "medium" },
  { id: "253", title: "meeting-rooms-ii", difficulty: "medium" },
  { id: "98", title: "validate-binary-search-tree", difficulty: "medium" },
  { id: "226", title: "invert-binary-tree", difficulty: "easy" },
  { id: "100", title: "same-tree", difficulty: "easy" },
  { id: "1143", title: "longest-common-subsequence", difficulty: "medium" },
  { id: "102", title: "binary-tree-level-order-traversal", difficulty: "medium" },
  { id: "230", title: "kth-smallest-element-in-a-bst", difficulty: "medium" },
  { id: "104", title: "maximum-depth-of-binary-tree", difficulty: "easy" },
  { id: "105", title: "construct-binary-tree-from-preorder-and-inorder-traversal", difficulty: "medium" },
  { id: "235", title: "lowest-common-ancestor-of-a-binary-search-tree", difficulty: "easy" },
  { id: "238", title: "product-of-array-except-self", difficulty: "medium" },
  { id: "242", title: "valid-anagram", difficulty: "easy" },
  { id: "371", title: "sum-of-two-integers", difficulty: "medium" },
  { id: "252", title: "meeting-rooms", difficulty: "easy" },
  { id: "121", title: "best-time-to-buy-and-sell-stock", difficulty: "easy" },
  { id: "124", title: "binary-tree-maximum-path-sum", difficulty: "hard" },
  { id: "125", title: "valid-palindrome", difficulty: "easy" },
];

export const problemMap: Record<Problem["title"], Problem> = problems.reduce(
  (map, problem) => {
    map[problem.title] = problem;
    return map;
  },
  {} as Record<Problem["title"], Problem>,
);

export const problemCounts = problems.reduce(
  (acc, problem) => {
    acc[problem.difficulty] += 1;
    return acc;
  },
  { easy: 0, medium: 0, hard: 0 },
);
