name: Storybook Tests

on: deployment_status

jobs:
  test-storybook:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event.deployment_status.environment == 'chromatic' && github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bunx playwright install --with-deps
      - run: bun run build-storybook
      - run: yes | bunx serve storybook-static -l 6006 &
      - run: bunx wait-on http://127.0.0.1:6006
      - run: bun run test-storybook --url http://127.0.0.1:6006 --ci
